### PR TITLE
Run pytest on CI

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by maxtremblay** [comment]
I am not really familiar with CI. But does this still publish the package on PyPi or it just runs the tests? Also, thanks for catching the error in the sparse.py file.

**Comment by messense** [comment]
It will publish to PyPI on git tag.

**Comment by messense** [comment]
The release process is

1. Increase version in https://github.com/maxtremblay/pyqec/blob/main/Cargo.toml#L3 and commit.
2. Run `git tag vX.Y.Z` and push the commit and the tag to GitHub, then CI will take care of publishing to PyPI.

**Comment by maxtremblay** [comment]
Awesome! Thanks a lot :smile:

**Pull request merged**
