### PR TITLE
Properly configure maturin-action

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by messense** [comment]
Looks like it needs to install dependencies first, then install pyqec with `pip install pyqec --no-index --find-links dist --force-reinstall` to ensure it's installed from local directory instead of PyPI.

**Comment by maxtremblay** [comment]
Wow, this is awesome. For real, yesterday I was telling a coworker that I need to figure out how to properly use GitHub actions to publish multiple versions on PyPi. And now, here you are helping with that today. I really appreciate it. 😄

**Comment by messense** [comment]
😀 BTW, consider upgrading pyo3 to [0.13.2](https://pyo3.rs/v0.13.2/migration.html#from-012-to-013) and use [abi3 feature](https://pyo3.rs/v0.13.2/building_and_distribution.html#py_limited_apiabi3) if possible, it'll greatly simplify CI, for example https://github.com/messense/crfs-rs/blob/main/.github/workflows/Python.yml

**Comment by maxtremblay** [comment]
Ok, I will try that. At least, now it seems to work on more platforms.

**Pull request merged**
